package api

const (
	QpIdentifier  = "identifier"
	QpGroup       = "group"
	QpStatus      = "status"
	QpShowKey     = "showkey"
	QpNewKey      = "newkey"
	QpCriticality = "criticality"
	QpWait        = "wait"
	QpSince       = "since"
	QpUntil       = "until"
	QpLast        = "last"
	QpLimit       = "limit"
	QpPivot       = "pivot"
	QpDelta       = "delta"
	QpSkip        = "skip"
	QpSource      = "source"
	QpValue       = "value"
	QpType        = "type"
	QpName        = "name"
	QpFilters     = "filters"
	QpUpdate      = "update"
	QpRaw         = "raw"
	QpGunzip      = "gunzip"
	QpUuid        = "uuid"
	QpGroupUuid   = "guuid"
	QpFormat      = "format"
	QpVersion     = "version"
	QpOS          = "os"
	QpBinary      = "binary"
	QpHash        = "hash"
)
