package api

const (
	qpIdentifier  = "identifier"
	qpGroup       = "group"
	qpStatus      = "status"
	qpShowKey     = "showkey"
	qpNewKey      = "newkey"
	qpCriticality = "criticality"
	qpWait        = "wait"
	qpSince       = "since"
	qpUntil       = "until"
	qpLast        = "last"
	qpLimit       = "limit"
	qpPivot       = "pivot"
	qpDelta       = "delta"
	qpSkip        = "skip"
	qpSource      = "source"
	qpValue       = "value"
	qpType        = "type"
	qpName        = "name"
	qpFilters     = "filters"
	qpUpdate      = "update"
	qpRaw         = "raw"
	qpGunzip      = "gunzip"
	qpUuid        = "uuid"
	qpGroupUuid   = "guuid"
	qpFormat      = "format"
	qpVersion     = "version"
)
