#!/bin/bash
set -e

DOC="doc"

echo "Generating EDR command documentation"
./scripts/cmdoc.sh > "$DOC/edr-commands.md"
# Adding EDR command documentation to commit
git add "$DOC/edr-commands.md"

echo "Running coverage"
./scripts/coverage.sh
# Adding coverage files to commit
git add .github/coverage/coverage.txt
git add .github/coverage/badge.svg

echo "Generating OpenAPI documentation"
GOOS=linux go run utilities/manager/*.go -openapi > "$DOC/admin.openapi.json"

# adding openapi files to commit
git add api/openapi_def.go
git add doc/admin.openapi.json

# files added to commit will not be seen in the commit message shown by git
# in text editor but those files will be added to the index anyway
git status
